export interface Dream100Contact {
  id: string;
  consultant_id: string;
  name: string;
  company: string;
  email: string;
  phone?: string;
  linkedin_profile?: string;
  source: 'LinkedIn' | 'Email List' | 'YouTube' | 'Referral';
  relationship: 'Prospect' | 'Client' | 'Vendor' | 'Promotional Partner';
  title?: string;
  preferred_communication: 'Email' | 'Call' | 'Text' | 'LinkedIn';
  latest_decision: 'Research' | 'Reached Out' | 'In Conversation' | '2nd Meeting' | 'Buy' | "Don't Buy" | 'Postpone' | 'Referral' | 'No Decision';
  next_contact_date?: string;
  is_dream_100: boolean;
  last_interaction?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  interaction_count?: number;
  conversion_probability?: number;
}

export const dream100Contacts: Dream100Contact[] = [
  {
    id: "contact-1",
    consultant_id: "consultant-1",
    name: "John Smith",
    company: "TechCorp Inc",
    email: "john@techcorp.com",
    phone: "+1-555-0123",
    linkedin_profile: "https://linkedin.com/in/johnsmith",
    source: "LinkedIn",
    relationship: "Prospect",
    title: "CEO",
    preferred_communication: "Email",
    latest_decision: "In Conversation",
    next_contact_date: "2025-08-08",
    is_dream_100: true,
    last_interaction: "2025-08-05",
    notes: "Interested in Q4 implementation. Budget approved. Needs board approval.",
    created_at: "2025-07-15T00:00:00Z",
    updated_at: "2025-08-05T10:30:00Z",
    interaction_count: 4,
    conversion_probability: 85
  },
  {
    id: "contact-2",
    consultant_id: "consultant-1",
    name: "Sarah Chen",
    company: "StartupX Labs",
    email: "sarah@startupx.com",
    phone: "+1-555-0124",
    linkedin_profile: "https://linkedin.com/in/sarahchen",
    source: "Referral",
    relationship: "Prospect",
    title: "Founder & CTO",
    preferred_communication: "LinkedIn",
    latest_decision: "Buy",
    next_contact_date: undefined,
    is_dream_100: true,
    last_interaction: "2025-08-06",
    notes: "Converted! Ready to start onboarding. Signed contract for Premium package.",
    created_at: "2025-07-20T00:00:00Z",
    updated_at: "2025-08-06T14:20:00Z",
    interaction_count: 6,
    conversion_probability: 100
  },
  {
    id: "contact-3",
    consultant_id: "consultant-1",
    name: "Mike Johnson",
    company: "BigCorp Enterprise",
    email: "mjohnson@bigcorp.com",
    phone: "+1-555-0125",
    linkedin_profile: "https://linkedin.com/in/mikejohnson",
    source: "Email List",
    relationship: "Prospect",
    title: "VP of Operations",
    preferred_communication: "Call",
    latest_decision: "2nd Meeting",
    next_contact_date: "2025-08-09",
    is_dream_100: true,
    last_interaction: "2025-08-04",
    notes: "Scheduled follow-up meeting with full team. Very promising.",
    created_at: "2025-07-10T00:00:00Z",
    updated_at: "2025-08-04T16:45:00Z",
    interaction_count: 5,
    conversion_probability: 70
  },
  {
    id: "contact-4",
    consultant_id: "consultant-1",
    name: "Emma Wilson",
    company: "FinTech Solutions",
    email: "emma@fintech.com",
    linkedin_profile: "https://linkedin.com/in/emmawilson",
    source: "LinkedIn",
    relationship: "Prospect",
    title: "Head of Strategy",
    preferred_communication: "Email",
    latest_decision: "Reached Out",
    next_contact_date: "2025-08-07",
    is_dream_100: true,
    last_interaction: "2025-08-03",
    notes: "Initial outreach sent. Waiting for response.",
    created_at: "2025-08-01T00:00:00Z",
    updated_at: "2025-08-03T09:15:00Z",
    interaction_count: 1,
    conversion_probability: 30
  },
  {
    id: "contact-5",
    consultant_id: "consultant-1",
    name: "David Rodriguez",
    company: "Global Retail Co",
    email: "d.rodriguez@globalretail.com",
    phone: "+1-555-0126",
    source: "YouTube",
    relationship: "Prospect",
    title: "Director of Innovation",
    preferred_communication: "Text",
    latest_decision: "Don't Buy",
    next_contact_date: undefined,
    is_dream_100: true,
    last_interaction: "2025-08-02",
    notes: "Not ready for implementation. Follow up in Q1 2026.",
    created_at: "2025-07-25T00:00:00Z",
    updated_at: "2025-08-02T11:30:00Z",
    interaction_count: 3,
    conversion_probability: 5
  },
  {
    id: "contact-6",
    consultant_id: "consultant-1",
    name: "Lisa Park",
    company: "HealthTech Innovations",
    email: "lisa@healthtech.com",
    linkedin_profile: "https://linkedin.com/in/lisapark",
    source: "LinkedIn",
    relationship: "Prospect",
    title: "Chief Medical Officer",
    preferred_communication: "Email",
    latest_decision: "In Conversation",
    next_contact_date: "2025-08-10",
    is_dream_100: true,
    last_interaction: "2025-08-05",
    notes: "Very interested in compliance features. Needs legal review.",
    created_at: "2025-07-18T00:00:00Z",
    updated_at: "2025-08-05T13:20:00Z",
    interaction_count: 4,
    conversion_probability: 65
  },
  {
    id: "contact-7",
    consultant_id: "consultant-1",
    name: "Alex Thompson",
    company: "Manufacturing Plus",
    email: "alex@mfgplus.com",
    phone: "+1-555-0127",
    source: "Referral",
    relationship: "Prospect",
    title: "Operations Manager",
    preferred_communication: "Call",
    latest_decision: "Research",
    next_contact_date: "2025-08-12",
    is_dream_100: true,
    last_interaction: undefined,
    notes: "New lead from existing client referral. High priority.",
    created_at: "2025-08-05T00:00:00Z",
    updated_at: "2025-08-05T00:00:00Z",
    interaction_count: 0,
    conversion_probability: 45
  },
  {
    id: "contact-8",
    consultant_id: "consultant-1",
    name: "Rachel Green",
    company: "EcoSustain Corp",
    email: "rachel@ecosustain.com",
    linkedin_profile: "https://linkedin.com/in/rachelgreen",
    source: "LinkedIn",
    relationship: "Prospect",
    title: "Sustainability Director",
    preferred_communication: "LinkedIn",
    latest_decision: "Postpone",
    next_contact_date: "2025-09-15",
    is_dream_100: true,
    last_interaction: "2025-08-04",
    notes: "Budget freeze until Q4. Very interested but timing is wrong.",
    created_at: "2025-07-22T00:00:00Z",
    updated_at: "2025-08-04T10:10:00Z",
    interaction_count: 3,
    conversion_probability: 60
  },
  {
    id: "contact-9",
    consultant_id: "consultant-1",
    name: "Tom Anderson",
    company: "Digital Marketing Pro",
    email: "tom@digitalmarketing.com",
    phone: "+1-555-0128",
    source: "Email List",
    relationship: "Prospect",
    title: "Agency Owner",
    preferred_communication: "Email",
    latest_decision: "Reached Out",
    next_contact_date: "2025-08-08",
    is_dream_100: true,
    last_interaction: "2025-08-06",
    notes: "Responded to initial outreach. Scheduling discovery call.",
    created_at: "2025-08-03T00:00:00Z",
    updated_at: "2025-08-06T08:30:00Z",
    interaction_count: 2,
    conversion_probability: 40
  },
  {
    id: "contact-10",
    consultant_id: "consultant-1",
    name: "Jennifer Walsh",
    company: "Legal Eagles LLP",
    email: "jennifer@legaleagles.com",
    linkedin_profile: "https://linkedin.com/in/jenniferwalsh",
    source: "Referral",
    relationship: "Prospect",
    title: "Managing Partner",
    preferred_communication: "Call",
    latest_decision: "2nd Meeting",
    next_contact_date: "2025-08-11",
    is_dream_100: true,
    last_interaction: "2025-08-06",
    notes: "Excellent fit. Bringing in senior partners for next meeting.",
    created_at: "2025-07-28T00:00:00Z",
    updated_at: "2025-08-06T15:45:00Z",
    interaction_count: 4,
    conversion_probability: 80
  },
  {
    id: "contact-11",
    consultant_id: "consultant-1",
    name: "Carlos Martinez",
    company: "Construction Dynamics",
    email: "carlos@constructiondyn.com",
    phone: "+1-555-0129",
    source: "YouTube",
    relationship: "Prospect",
    title: "Project Director",
    preferred_communication: "Text",
    latest_decision: "Research",
    next_contact_date: "2025-08-09",
    is_dream_100: false,
    last_interaction: undefined,
    notes: "Found us through YouTube channel. Interested in project management features.",
    created_at: "2025-08-06T00:00:00Z",
    updated_at: "2025-08-06T00:00:00Z",
    interaction_count: 0,
    conversion_probability: 25
  },
  {
    id: "contact-12",
    consultant_id: "consultant-1",
    name: "Priya Patel",
    company: "AI Robotics Inc",
    email: "priya@airobotics.com",
    linkedin_profile: "https://linkedin.com/in/priyapatel",
    source: "LinkedIn",
    relationship: "Prospect",
    title: "Chief Technology Officer",
    preferred_communication: "Email",
    latest_decision: "In Conversation",
    next_contact_date: "2025-08-07",
    is_dream_100: true,
    last_interaction: "2025-08-05",
    notes: "Technical deep-dive scheduled. Impressed with automation capabilities.",
    created_at: "2025-07-30T00:00:00Z",
    updated_at: "2025-08-05T11:15:00Z",
    interaction_count: 3,
    conversion_probability: 75
  },
  {
    id: "contact-13",
    consultant_id: "consultant-1",
    name: "Robert Kim",
    company: "Food Service Excellence",
    email: "robert@foodservice.com",
    phone: "+1-555-0130",
    source: "Email List",
    relationship: "Prospect",
    title: "Regional Manager",
    preferred_communication: "Call",
    latest_decision: "Reached Out",
    next_contact_date: "2025-08-10",
    is_dream_100: true,
    last_interaction: "2025-08-04",
    notes: "Initial contact made. Scheduling follow-up call this week.",
    created_at: "2025-08-02T00:00:00Z",
    updated_at: "2025-08-04T14:20:00Z",
    interaction_count: 1,
    conversion_probability: 35
  },
  {
    id: "contact-14",
    consultant_id: "consultant-1",
    name: "Michelle Brown",
    company: "Education Forward",
    email: "michelle@educationforward.com",
    linkedin_profile: "https://linkedin.com/in/michellebrown",
    source: "Referral",
    relationship: "Prospect",
    title: "Program Director",
    preferred_communication: "LinkedIn",
    latest_decision: "Referral",
    next_contact_date: "2025-08-14",
    is_dream_100: true,
    last_interaction: "2025-08-03",
    notes: "Not a fit but referred us to 3 other education companies. Great connection.",
    created_at: "2025-07-26T00:00:00Z",
    updated_at: "2025-08-03T16:30:00Z",
    interaction_count: 2,
    conversion_probability: 10
  },
  {
    id: "contact-15",
    consultant_id: "consultant-1",
    name: "Steve Johnson",
    company: "Logistics Leaders",
    email: "steve@logisticsleaders.com",
    phone: "+1-555-0131",
    source: "LinkedIn",
    relationship: "Prospect",
    title: "Supply Chain Director",
    preferred_communication: "Email",
    latest_decision: "Research",
    next_contact_date: "2025-08-11",
    is_dream_100: true,
    last_interaction: undefined,
    notes: "Large enterprise prospect. Need to research their current systems first.",
    created_at: "2025-08-04T00:00:00Z",
    updated_at: "2025-08-04T00:00:00Z",
    interaction_count: 0,
    conversion_probability: 50
  }
];

export const pipelineStats = {
  research: 4,
  reachedOut: 3,
  inConversation: 3,
  secondMeeting: 2,
  buy: 1,
  dontBuy: 1,
  postpone: 1,
  referral: 1
};

export const importTemplate = {
  headers: [
    'Name*',
    'Company*',
    'Email*',
    'Phone',
    'LinkedIn Profile',
    'Source',
    'Relationship',
    'Title',
    'Preferred Communication',
    'Notes'
  ],
  sampleData: [
    [
      'John Doe',
      'Example Corp',
      'john@example.com',
      '+1-555-0000',
      'https://linkedin.com/in/johndoe',
      'LinkedIn',
      'Prospect',
      'CEO',
      'Email',
      'Met at conference'
    ]
  ]
};